In [ ]:
#merge

import pandas as pd
Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,2,3,4],"D":["a","b","c","d"]})
pd.merge(Df1,Df2)

   A  B  D
0  1  A  a
1  2  B  b
2  3  C  c
3  4  D  d

In [ ]:
#merge follow on value

Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,2,3,4],"B":["a","b","c","d"]})
pd.merge(Df1,Df2,on="B")

Empty DataFrame
Columns: [A_x, B, A_y]
Index: []

In [ ]:
#inner merge
Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,2,3,4],"C":["a","b","c","d"]})
pd.merge(Df1,Df2,on="A",how = 'inner',indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

In [ ]:
#outer merge(union)
Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,2,3,4],"C":["a","b","c","d"]})
pd.merge(Df1,Df2,on="A",how = 'outer',indicator=True)

   A  B  C _merge
0  1  A  a   both
1  2  B  b   both
2  3  C  c   both
3  4  D  d   both

In [ ]:
#left merge ()
Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,5,7,4],"C":["a","b","c","d"]})
pd.merge(Df1,Df2,on="A",how = 'left',indicator=True)

   A  B    C     _merge
0  1  A    a       both
1  2  B  NaN  left_only
2  3  C  NaN  left_only
3  4  D    d       both

In [ ]:
#right merge
Df1 = pd.DataFrame({"A":[1,2,3,4],"B":["A","B","C","D"]})
Df2 = pd.DataFrame({"A":[1,5,7,4],"C":["a","b","c","d"]})
pd.merge(Df1,Df2,on="A",how = 'right',indicator=True)

   A    B  C      _merge
0  1    A  a        both
1  5  NaN  b  right_only
2  7  NaN  c  right_only
3  4    D  d        both

In [ ]:
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"A":[1,5,7,4,5],"B":["a","b","c","d","e"]})
pd.merge(Df1,Df2,left_index=True,right_index=True)

   A_x B_x  A_y B_y
0    1   A    1   a
1    2   B    5   b
2    3   C    7   c
3    4   D    4   d
4    5   E    5   e

In [ ]:
#remove x,y add name use suffix
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"A":[1,5,7,4,5],"B":["a","b","c","d","e"]})
pd.merge(Df1,Df2,left_index=True,right_index=True,suffixes=('Id','name'))

   AId BId  Aname Bname
0    1   A      1     a
1    2   B      5     b
2    3   C      7     c
3    4   D      4     d
4    5   E      5     e

In [ ]:
import pandas as pd

Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"C":[1,5,7,4,5],"D":["a","b","c","d","e"]})
Df2.join(Df1)

   C  D  A  B
0  1  a  1  A
1  5  b  2  B
2  7  c  3  C
3  4  d  4  D
4  5  e  5  E

In [ ]:
#index in join

Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]},index=["@","#","a",2,"^"])
Df2 = pd.DataFrame({"C":[1,5,7,4,5],"D":["a","b","c","d","e"]},index=["@","#","a",2,"^"])
Df2.join(Df1)

   C  D  A  B
@  1  a  1  A
#  5  b  2  B
a  7  c  3  C
2  4  d  4  D
^  5  e  5  E

In [ ]:
#change index value
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]},index=["@","#","a",2,"^"])
Df2 = pd.DataFrame({"C":[1,5,7,4,5],"D":["a","b","c","d","e"]},index=["^",2,"b",3,"*"])
Df2.join(Df1)

   C  D    A    B
^  1  a  5.0    E
2  5  b  4.0    D
b  7  c  NaN  NaN
3  4  d  NaN  NaN
*  5  e  NaN  NaN

In [ ]:
#inner join
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"C":["A","B"], "D":["E","F"]})
Df1.join(Df2,how='inner')

   A  B  C  D
0  1  A  A  E
1  2  B  B  F

In [ ]:
#outer join
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"C":["A","B"], "D":["E","F"]})
Df1.join(Df2,how='outer')

   A  B    C    D
0  1  A    A    E
1  2  B    B    F
2  3  C  NaN  NaN
3  4  D  NaN  NaN
4  5  E  NaN  NaN

In [ ]:
#left join
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"C":["A","B"], "D":["E","F"]})
Df1.join(Df2,how='left')

   A  B    C    D
0  1  A    A    E
1  2  B    B    F
2  3  C  NaN  NaN
3  4  D  NaN  NaN
4  5  E  NaN  NaN

In [ ]:
#right join
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"C":["A","B"], "D":["E","F"]})
Df1.join(Df2,how='right')

   A  B  C  D
0  1  A  A  E
1  2  B  B  F

In [ ]:
#suffixes in join (left and right)
Df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":["A","B","C","D","E"]})
Df2 = pd.DataFrame({"A":[1,5,7,4,5],"B":["a","b","c","d","e"]})
Df1.join(Df2,lsuffix=True,rsuffix=True)

   ATrue BTrue  ATrue BTrue
0      1     A      1     a
1      2     B      5     b
2      3     C      7     c
3      4     D      4     d
4      5     E      5     e

In [ ]:
import pandas as pd

# FIRST DATAFRAME
df1 = pd.DataFrame({
    "rollno": [1, 2, 3, 4],
    "name": ["Aman", "Neha", "Ravi", "Sara"],
    "subject": ["Math", "Science", "English", "CS"],
    "marks": [85, 90, 78, 88]
})

# SECOND DATAFRAME
df2 = pd.DataFrame({
    "rollno": [1, 2, 3, 4],
    "department": ["CSE", "ECE", "ME", "IT"],
    "annual": [300000, 350000, 280000, 400000],
    "father": ["Ram", "Shyam", "Mohan", "Amit"]
})

#  SET INDEX
df1 = df1.set_index("rollno")
df2 = df2.set_index("rollno")

#  MERGE USING INDEX
result = pd.merge(df1, df2, left_index=True, right_index=True)
print(result)

        name  subject  marks department  annual father
rollno
1       Aman     Math     85        CSE  300000    Ram
2       Neha  Science     90        ECE  350000  Shyam
3       Ravi  English     78         ME  280000  Mohan
4       Sara       CS     88         IT  400000   Amit